wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1670296573.636874
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.13.5
      8:
      - 5
eps:
  desc: null
  value:
  - 0.1
  - 0.01
  - 0.02
  - 0.03
  - 0.04
  - 0.05
min_sample:
  desc: null
  value:
  - 6
  - 7
  - 8
  - 9
  - 10
