wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1670307180.617809
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.13.5
      8:
      - 5
    viz:
      silhouette_plot:
        historyFieldSettings:
          key: silhouette_plot
          x-axis: _step
        id: wandb/silhouette_/v1
eps:
  desc: null
  value: 0.05
min_sample:
  desc: null
  value: 9
